### ISSUE TITLE
Request for Dataset Source

### ISSUE THREAD

**Issue by THITIWATKKK** [curlsloth/Capstone_Spotify-Sequential-Skip-Prediction#1]
Hello,

I'm interested in replicating and potentially extending the work you've done in this repository. However, I've noticed that the original dataset link from the AIcrowd challenge is no longer accessible. Would you happen to have a saved copy of the dataset or know where I might obtain it? Any guidance would be greatly appreciated!

Thank you for your time and for sharing this project!

**Comment by curlsloth** [comment]
Thank you for reaching out and please see my email. :)
